### ISSUE TITLE
Broken CI for building packages

### ISSUE THREAD

**Issue by bedroge** [EESSI/filesystem-layer#64]
This suddenly stopped working in December, due to an issue with building .deb packages:
```
/usr/local/bundle/gems/fpm-1.11.0/lib/fpm/package/deb.rb:495:in `block in output': uninitialized constant FPM::Package::Deb::Zlib (NameError)
167	from <internal:kernel>:90:in `tap'
168	from /usr/local/bundle/gems/fpm-1.11.0/lib/fpm/package/deb.rb:494:in `output'
169	from /usr/local/bundle/gems/fpm-1.11.0/lib/fpm/command.rb:487:in `execute'
170	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
171	from /usr/local/bundle/gems/fpm-1.11.0/lib/fpm/command.rb:574:in `run'
172	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
173	from /usr/local/bundle/gems/fpm-1.11.0/bin/fpm:7:in `<top (required)>'
174	from /usr/local/bundle/bin/fpm:23:in `load'
175	from /usr/local/bundle/bin/fpm:23:in `<main>'
```

We're using this Github Action:
https://github.com/bpicode/github-action-fpm
This wasn't changed, and it's still using the same fpm version. However, the base layer with Ruby was changed in December because of a new Ruby release (3.0.0), so I suspect this is related. Strangely, I now seem to have the issue too when doing some manually tests with an older Ruby container...

The same issue is discussed here:
https://github.com/jordansissel/fpm/issues/1739

And there's a PR for fixing the issue in fpm:
https://github.com/jordansissel/fpm/pull/1740
But that's still waiting to be merged...

**Comment by bedroge** [comment]
Okay, it's definitely related to the Ruby version.
```
apk --no-cache add build-base
apk --no-cache add rpm
apk --no-cache add tar
apk --no-cache add zip
gem install --no-document fpm -v 1.11.0

cd
mkdir -p package/test

fpm -n testpkg -v 1.0 -t deb -a all -s dir -C ./package test
```
This does work fine in an older Ruby container (e.g. `ruby:2-alpine`), but doesn't work in `ruby:alpine`:
```
/usr/local/bundle/gems/fpm-1.11.0/lib/fpm/package/deb.rb:495:in `block in output': uninitialized constant FPM::Package::Deb::Zlib (NameError)
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/fpm-1.11.0/lib/fpm/package/deb.rb:494:in `output'
	from /usr/local/bundle/gems/fpm-1.11.0/lib/fpm/command.rb:487:in `execute'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /usr/local/bundle/gems/fpm-1.11.0/lib/fpm/command.rb:574:in `run'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /usr/local/bundle/gems/fpm-1.11.0/bin/fpm:7:in `<top (required)>'
	from /usr/local/bundle/bin/fpm:23:in `load'
	from /usr/local/bundle/bin/fpm:23:in `<main>'
```

I don't understand why it works in Ruby 2 though (and it still seems to be a bug in FPM anyway), as I can't just call `Zlib::<whatever>` from a simple test script or interactive Ruby session... But as long as it isn't fixed (i.e. the PR isn't merged), we can work around it by reverting to Ruby 2.

**Comment by bedroge** [comment]
Fixed by https://github.com/bpicode/github-action-fpm/issues/3 and https://github.com/bpicode/github-action-fpm/commit/e76c0e2166030f4691d641a700b16958c7d12f5d.
